# Generated by Django 4.2.2 on 2023-06-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Imagenes'),
        ),
    ]
