# Generated by Django 4.2.2 on 2023-06-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_file_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.FileField(upload_to='images/', verbose_name='Imagenes'),
        ),
    ]
