# Generated by Django 4.2.2 on 2023-06-28 21:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_file_post_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(upload_to=users.models.images_path),
        ),
    ]
