# Generated by Django 4.2.2 on 2023-06-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_file_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='format',
            field=models.CharField(choices=[('JPEG', 'JPEG'), ('DICOM', 'DICOM')], default='DICOM', max_length=5),
            preserve_default=False,
        ),
    ]
