# Generated by Django 4.2.2 on 2023-06-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='format',
            field=models.CharField(choices=[('JPEG', 'JPEG'), ('DICOM', 'DICOM'), ('jpg', 'JPEG')], max_length=5),
        ),
    ]
