# Generated by Django 4.2.2 on 2023-06-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='format',
            field=models.CharField(choices=[('JPEG, JPG', 'JPEG/JPG'), ('DICOM', 'DICOM')], max_length=9),
        ),
    ]
