# Generated by Django 4.2.2 on 2023-06-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_file_format'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
