# Generated by Django 4.2.2 on 2023-07-04 09:37

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category_post_clinical_case_post_clinical_signs_and_more'),
        ('users', '0013_filejpg_filedicom'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('JPEG, JPG', 'JPEG/JPG'), ('DICOM', 'DICOM')], max_length=9)),
                ('axial_image', models.FileField(upload_to=users.models.images_path)),
                ('sagital_image', models.FileField(upload_to=users.models.images_path)),
                ('coronal_image', models.FileField(upload_to=users.models.images_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.DeleteModel(
            name='FileDICOM',
        ),
    ]
