# Generated by Django 4.2.2 on 2023-07-04 10:12

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_filepost_accepted_data_use_filepost_cie_11_tagging_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepost',
            name='axial_image',
            field=models.ImageField(upload_to=users.models.images_path),
        ),
        migrations.AlterField(
            model_name='filepost',
            name='coronal_image',
            field=models.ImageField(upload_to=users.models.images_path),
        ),
        migrations.AlterField(
            model_name='filepost',
            name='sagital_image',
            field=models.ImageField(upload_to=users.models.images_path),
        ),
    ]
