# Generated by Django 4.2.2 on 2023-07-04 10:49

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_filepost_axial_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepost',
            name='axial_image',
            field=models.FileField(null=True, upload_to=users.models.images_path),
        ),
        migrations.AlterField(
            model_name='filepost',
            name='coronal_image',
            field=models.FileField(null=True, upload_to=users.models.images_path),
        ),
        migrations.AlterField(
            model_name='filepost',
            name='sagital_image',
            field=models.FileField(null=True, upload_to=users.models.images_path),
        ),
    ]
