# Generated by Django 4.2.2 on 2023-07-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_filepost_axial_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepost',
            name='coronal_image',
        ),
        migrations.RemoveField(
            model_name='filepost',
            name='sagital_image',
        ),
    ]
