# Generated by Django 4.2.2 on 2023-07-04 11:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_filepost_coronal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepost',
            name='coronal_image',
            field=models.FileField(null=True, upload_to=users.models.images_path),
        ),
        migrations.AddField(
            model_name='filepost',
            name='sagital_image',
            field=models.FileField(null=True, upload_to=users.models.images_path),
        ),
    ]
