# Generated by Django 4.2.2 on 2023-07-04 11:14

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_filepost_coronal_image_filepost_sagital_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepost',
            name='axial_image',
        ),
        migrations.RemoveField(
            model_name='filepost',
            name='coronal_image',
        ),
        migrations.RemoveField(
            model_name='filepost',
            name='sagital_image',
        ),
        migrations.AddField(
            model_name='filepost',
            name='images',
            field=models.FileField(default='totusbl', upload_to=users.models.images_path),
            preserve_default=False,
        ),
    ]
