# Generated by Django 4.2.2 on 2023-07-04 11:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_filepost_axial_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepost',
            name='images',
        ),
        migrations.AddField(
            model_name='filepost',
            name='axial_image',
            field=models.ImageField(default='totsubl', upload_to=users.models.images_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filepost',
            name='coronal_image',
            field=models.ImageField(default='totusbl', upload_to=users.models.images_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filepost',
            name='sagital_image',
            field=models.ImageField(default='totusbl', upload_to=users.models.images_path),
            preserve_default=False,
        ),
    ]
