# Generated by Django 4.2.2 on 2023-07-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_filepost_images_filepost_axial_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepost',
            old_name='axial_image',
            new_name='imagenes',
        ),
        migrations.RemoveField(
            model_name='filepost',
            name='coronal_image',
        ),
        migrations.RemoveField(
            model_name='filepost',
            name='sagital_image',
        ),
    ]
