# Generated by Django 4.2.2 on 2023-07-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_axial_image_filepost_imagenes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepost',
            old_name='imagenes',
            new_name='images',
        ),
    ]
