# Generated by Django 4.2.2 on 2023-07-04 14:14

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_imagenes_filepost_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepost',
            name='header_image',
            field=models.ImageField(default='test', upload_to=users.models.images_path),
            preserve_default=False,
        ),
    ]
