# Generated by Django 4.2.2 on 2023-07-05 15:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_filepost_cie_11_tagging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepost',
            name='images',
        ),
        migrations.AddField(
            model_name='filepost',
            name='axial_images',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.images_path),
        ),
        migrations.AddField(
            model_name='filepost',
            name='coronal_images',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.images_path),
        ),
        migrations.AddField(
            model_name='filepost',
            name='sagital_images',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.images_path),
        ),
    ]
