# Generated by Django 4.2.2 on 2023-07-06 14:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_filepost_images_filepost_axial_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepost',
            name='highlighted_image1',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.images_path),
        ),
        migrations.AddField(
            model_name='filepost',
            name='highlighted_image2',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.images_path),
        ),
    ]
