# Generated by Django 4.2.2 on 2023-07-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_filepost_highlighted_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepost',
            name='accepted_data_use',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, null=True),
        ),
    ]
