# Generated by Django 4.2.2 on 2023-07-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_filepost_accepted_data_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepost',
            name='format',
            field=models.CharField(blank=True, choices=[('JPEG, JPG', 'JPEG/JPG'), ('DICOM', 'DICOM')], max_length=9, null=True),
        ),
    ]
