# Generated by Django 4.2.2 on 2023-07-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_filepost_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepost',
            name='other_interested_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
