# Generated by Django 4.2.2 on 2023-07-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_filepost_other_interested_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepost',
            name='highlighted_image1',
        ),
        migrations.RemoveField(
            model_name='filepost',
            name='highlighted_image2',
        ),
        migrations.AlterField(
            model_name='filepost',
            name='accepted_data_use',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True),
        ),
    ]
