# Generated by Django 4.2.2 on 2023-07-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
