# Generated by Django 4.2.2 on 2023-07-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepost',
            name='cie_11_tagging',
            field=models.CharField(blank=True, choices=[('', '---------'), ('DB90 Enfermedad infecciosa del hígado', 'DB90 Enfermedad infecciosa del hígado'), ('DB91 Insuficiencia hepática aguda o subaguda', 'DB91 Insuficiencia hepática aguda o subaguda'), ('DB92/DB94 Hepatopatía grasa', 'DB92/DB94 Hepatopatía grasa'), ('DB93 Fibrosis o cirrosis hepática', 'DB93 Fibrosis o cirrosis hepática'), ('DB95 Hepatopatía tóxica o provocada por medicamentos', 'DB95 Hepatopatía tóxica o provocada por medicamentos'), ('DB96 Enfermedad hepática autoinmune', 'DB96 Enfermedad hepática autoinmune'), ('DB97 Algunas hepatopatías inflamatorias especificadas', 'DB97 Algunas hepatopatías inflamatorias especificadas'), ('DB98 Trastornos vasculares del hígado', 'DB98 Trastornos vasculares del hígado'), ('DB99 Algunas enfermedades especificadas del hígado', 'DB99 Algunas enfermedades especificadas del hígado'), ('Neoplasias del hígado', 'Neoplasias del hígado'), ('LB20.0 Anomalías estructurales del desarrollo prenatal del hígado', 'LB20.0 Anomalías estructurales del desarrollo prenatal del hígado'), ('5C90 Enfermedad hepática metabólica o transportadora', '5C90 Enfermedad hepática metabólica o transportadora'), ('Hepatitis viral', 'Hepatitis viral'), ('DB9Z Enfermedades del hígado, sin especificación', 'DB9Z Enfermedades del hígado, sin especificación'), ('Otras', 'Otras')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filepost',
            name='interested_region',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Segmento 1', 'Segmento 1'), ('Segmento 2', 'Segmento 2'), ('Segmento 3', 'Segmento 3'), ('Segmento 4', 'Segmento 4'), ('Segmento 5', 'Segmento 5'), ('Segmento 6', 'Segmento 6'), ('Segmento 7', 'Segmento 7'), ('Segmento 8', 'Segmento 8'), ('Difusa', 'Difusa'), ('Subcapsular', 'Subcapsular')], max_length=100, null=True),
        ),
    ]
