# Generated by Django 4.2.2 on 2023-07-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_filepost_cie_11_tagging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepost',
            name='descripcion_axial',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='filepost',
            name='descripcion_coronal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='filepost',
            name='descripcion_sagital',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
