# Generated by Django 4.2.2 on 2023-07-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_filepost_descripcion_axial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepost',
            old_name='descripcion_axial',
            new_name='axial_description',
        ),
        migrations.RenameField(
            model_name='filepost',
            old_name='descripcion_coronal',
            new_name='coronal_description',
        ),
        migrations.RenameField(
            model_name='filepost',
            old_name='descripcion_sagital',
            new_name='sagital_description',
        ),
    ]
