# Generated by Django 4.2.3 on 2023-09-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_rename_descripcion_axial_filepost_axial_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepost',
            name='category',
            field=models.CharField(choices=[('Abdomen', 'Abdomen'), ('Torax', 'Torax'), ('Ginecología', 'Ginecología'), ('Pediatría', 'Pediatría'), ('Neurología', 'Neurología'), ('Musculoesquelético', 'Musculoesquelético'), ('Otras', 'Otras')], default='Abdomen', max_length=20),
        ),
    ]
