# Generated by Django 4.2.2 on 2023-07-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Abdomen', 'Abdomen'), ('Torax', 'Torax'), ('Ginecología', 'Ginecología'), ('Pediatría', 'Pediatría'), ('Neurología', 'Neurología'), ('Musculoesquelético', 'Musculoesquelético'), ('Otras', 'Otras')], default='Abdomen', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='clinical_case',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='clinical_signs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='doppler',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fisiopathology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='medical_findings',
            field=models.CharField(choices=[('Alta (confirmación anatomopatológica/quirúrgica)', 'Alta (confirmación anatomopatológica/quirúrgica)'), ('Moderada', 'Moderada'), ('Baja', 'Baja')], default='Alta (confirmación anatomopatológica/quirúrgica)', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='medical_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pediatrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='preparation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='radiopedia_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sequential',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seram_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
